### ISSUE TITLE
[BE] 도메인별 API 리팩토링

### ISSUE THREAD

**Issue by LeeGoh** [boostup-project/boostup-project#246]
## 📝 Github Issue
도메인별 API 리팩토링

## 💫 Branch
feat/이슈요약#[이슈번호]
> ex) refactor/member#246

## ✔️ Check List
> 이슈 체크리스트

- [x] Lesson 도메인
- [x] Member 도메인
- [x] Suggest 도메인
- [x] Bookmark 도메인
- [x] Review 도메인
- [x] Chat 도메인

<br>

**Comment by mozzi327** [comment]
고생쓰 ~~~
