### ISSUE TITLE
[BE] 개발 환경 세팅

### ISSUE THREAD

**Issue by Quartz614** [boostup-project/boostup-project#3]
## 📝 Github Issue
[BE] 개발 환경 세팅

## ✔️ Check List
> 이슈 체크리스트

- [x] 깃허브 세팅
- [x] 스프링 부트 프로젝트 추가
- [x] build.grade 세팅
- [x] ignore 파일 추가

**Comment by mozzi327** [comment]
고생하셨습니다!
