### ISSUE TITLE
[FE/BE] API 명세서 작성

### ISSUE THREAD

**Issue by mozzi327** [boostup-project/boostup-project#4]
## 📝 Github Issue
기능사항별 API 명세서 작성

### 권한 인증
- [x] 로그인(+OAuth)
- [x] 로그아웃
- [x] 비밀번호 찾기
- [x] 토큰 리이슈

### 회원가입
- [x] 회원가입(+OAuth)

### 검색
- [x] 상세 검색

### 메인페이지 조회
- [x] 강사 전체 조회
- [x] 강사 언어 카테고리 별 조회

### 마이페이지
- [x] 마이페이지 조회
- [x] 프로필 수정(이미지)
- [x] 프로필 수정(유저정보)
- [x] 회원탈퇴

### 과외
- [x] 과외 등록
- [x] 마이페이지 과외 목록 조회
- [x] 상세페이지 과외 내용 조회
- [x] 과외 내용 수정
- [x] 과외 삭제

### 과외 신청
- [x] 신청 프로세스 1(등록)
- [x] 신청 프로세스 2(강사 수락, 거절)
- [x] 신청 프로세스 3(결제 진행 URL 요청)
- [x] 신청 프로세스 4(결제 완료)
- [x] 신청 프로세스 5(결제 취소)
- [x] 신청 프로세스 6(결제 실패)
- [x] 마이페이지 조회(강사용)
- [x] 마이페이지 조회(학생용)
- [x] 신청 삭제

### 리뷰
- [x] 리뷰 등록
- [x] 상세페이지 리뷰 조회
- [x] 마이페이지 리뷰 조회
- [x] 리뷰 수정
- [x] 리뷰 삭제

### 북마크
- [x] 마이페이지 북마크 조회
- [x] 북마크 추가 / 삭제

### 실시간 채팅
- [x] 추후 작성 예정

**Comment by Quartz614** [comment]
👍
